name: Scheduled Job
# https://crontab.guru/ for syntax
on:
  schedule:
    - cron: "*/5 * * * *" 

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: "16"
      - name: install NPM
        run: npm install
      - name: run script
        run: node migrate.js
